package model;

import java.util.GregorianCalendar; //importuar kalendari gregorian per kalendarin e perdorur ne kod

public class Announcement {

	private int systemId; 
	private GregorianCalendar date;
	private String title, description;
	
	public Announcement(String title, String description) {
		this(new GregorianCalendar(), title, description);
	}

	//Te announcement merret data, titullu, perhskimi i announcement
	public Announcement(GregorianCalendar date, String title, String description) {
		super();
		this.date = date;
		this.title = title;
		this.description = description;
	}

	//Ketu merret data
	public GregorianCalendar getDate() {
		return date;
	}
	//Ketu merret Id e sistemit
	public int getSystemId() {
		return systemId;
	}
     //i jepet vlera e ID systemId
	public void setSystemId(int systemId) {
		this.systemId = systemId;
	}
//Kalohet vlera e dates te date
	public void setDate(GregorianCalendar date) {
		this.date = date;
	}
//merret vlera e title
	public String getTitle() {
		return title;
	}
//jepet vlera e titullit te title
	public void setTitle(String title) {
		this.title = title;
	}
//mere vlera e description
	public String getDescription() {
		return description;
	}
//kalohet vlera e pershkrimit te description
	public void setDescription(String description) {
		this.description = description;
	}

	@Override
	public int hashCode() {
		final int prime = 31; //this means that this value can not be modified in the future
		int result = 1;
		result = prime * result + ((date == null) ? 0 : date.hashCode()); //hashCode() returns an integer value, generated by a hashing algorithm
		result = prime * result + ((description == null) ? 0 : description.hashCode());
		result = prime * result + ((title == null) ? 0 : title.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (!(obj instanceof Announcement)) {
			return false; //it compares the instance with type. It returns either true or false
		}
		Announcement other = (Announcement) obj;
		if (date == null) {
			if (other.date != null) {
				return false; //it returns false if date is null
			}
		} else if (!date.equals(other.date)) {
			return false;
		}
		if (description == null) {
			if (other.description != null) { //returns false if description is false
				return false;
			}
		} else if (!description.equals(other.description)) {
			return false;
		}
		if (title == null) {
			if (other.title != null) {
				return false; //returns false if title is null
			}
		} else if (!title.equals(other.title)) {
			return false;
		}
		return true;
	}

}
